kind: CronJob
apiVersion: batch/v1
metadata:
  name: backup-vm-cronjob
  namespace: default
  uid: 68b21e23-d819-404b-b0b3-6ca53e0968de
  resourceVersion: '6710476'
  generation: 1
  creationTimestamp: '2023-09-19T10:29:27Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: batch/v1
      time: '2023-09-19T10:29:27Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:concurrencyPolicy: {}
          f:failedJobsHistoryLimit: {}
          f:jobTemplate:
            f:spec:
              f:template:
                f:spec:
                  f:containers:
                    k:{"name":"backup-vm-cronjob"}:
                      .: {}
                      f:args: {}
                      f:image: {}
                      f:imagePullPolicy: {}
                      f:name: {}
                      f:resources: {}
                      f:terminationMessagePath: {}
                      f:terminationMessagePolicy: {}
                  f:dnsPolicy: {}
                  f:restartPolicy: {}
                  f:schedulerName: {}
                  f:securityContext: {}
                  f:terminationGracePeriodSeconds: {}
          f:schedule: {}
          f:successfulJobsHistoryLimit: {}
          f:suspend: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: batch/v1
      time: '2023-10-01T03:02:11Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:lastScheduleTime: {}
          f:lastSuccessfulTime: {}
      subresource: status
spec:
  schedule: 0 3 */14,15,16,17,18,19,20,21 * 2
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: backup-vm-cronjob
              image: nthub.azurecr.io/backup-vm:latest
              args:
                - pwsh
                - '-Command'
                - ./main.ps1
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
status:
  lastScheduleTime: '2023-10-01T03:00:00Z'
  lastSuccessfulTime: '2023-10-01T03:02:11Z'
