name: Kubescape Scan

on:
  push:
    branches:
      - main

jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Kubescape
        run: |
          curl -sL https://github.com/armosec/kubescape/releases/download/v2.0.155/kubescape-v2.0.155-linux-amd64.tar.gz | tar xz
          sudo mv kubescape /usr/local/bin/
      - name: Run Kubescape
        run: |
          kubescape scan -f .