name: Kubescape Scan

on:
  push:
    branches:
      - main

jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Kubescape
        run: |
          sudo add-apt-repository ppa:kubescape/kubescape
          sudo apt update
          sudo apt install kubescape
      - name: Run Kubescape
        run: |
         kubescape scan *.yaml
