name: Kubescape Scan

on:
  push:
    branches:
      - main

jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Kubescape
        run: |
          curl -sL https://github.com/kubescape/kubescape/releases/download/v2.9.1/kubescape-arm64-ubuntu-latest | tar xz
          sudo mv kubescape /usr/local/bin/
      - name: Run Kubescape
        run: |
          kubescape scan -f .- name: Install Kubescape
